#!/usr/bin/env bash
#
# Hestia installer — idempotent. Run from the repo root on the devbox:
#
#     sudo bash deploy/install.sh
#
# Re-running is safe: it syncs the latest code, preserves the existing env/token,
# keeps the database, and restarts the services. It does NOT touch cloudflared or
# register the claude.ai connector — those are manual steps in docs/DEPLOY.md.

set -euo pipefail

APP_USER="hestia"
APP_DIR="/opt/hestia"
DATA_DIR="/var/lib/hestia"
ETC_DIR="/etc/hestia"
ENV_FILE="${ETC_DIR}/hestia.env"
PYTHON="${PYTHON:-python3}"

log() { printf '\033[36m==>\033[0m %s\n' "$*"; }
die() { printf '\033[31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "run as root (sudo bash deploy/install.sh)"
[[ -f "app/main.py" ]] || die "run this from the repo root (app/main.py not found)"
command -v rsync >/dev/null || die "rsync is required (apt install rsync)"
command -v "$PYTHON" >/dev/null || die "$PYTHON not found"

# 1) system user (no login shell) ----------------------------------------- #
if ! id "$APP_USER" >/dev/null 2>&1; then
  log "creating system user '$APP_USER'"
  useradd --system --home "$APP_DIR" --shell /usr/sbin/nologin "$APP_USER"
else
  log "user '$APP_USER' already exists"
fi

# 2) directories ----------------------------------------------------------- #
log "ensuring directories"
install -d -o "$APP_USER" -g "$APP_USER" "$APP_DIR" "$DATA_DIR"
install -d -o "$APP_USER" -g "$APP_USER" -m 0750 "$ETC_DIR"

# 3) sync code (exclude local junk) --------------------------------------- #
log "syncing code -> $APP_DIR"
rsync -a --delete \
  --exclude '.venv' --exclude '.git' --exclude '__pycache__' \
  --exclude '*.db' --exclude '*.db-*' --exclude '*.log' \
  --exclude '.pytest_cache' --exclude '*.egg-info' \
  ./ "$APP_DIR/"
chown -R "$APP_USER:$APP_USER" "$APP_DIR"

# 4) venv + install ------------------------------------------------------- #
if [[ ! -x "$APP_DIR/.venv/bin/python" ]]; then
  log "creating venv"
  sudo -u "$APP_USER" "$PYTHON" -m venv "$APP_DIR/.venv"
fi
log "installing dependencies"
sudo -u "$APP_USER" "$APP_DIR/.venv/bin/pip" install -q -U pip
if [[ -f "$APP_DIR/requirements.lock" ]]; then
  sudo -u "$APP_USER" "$APP_DIR/.venv/bin/pip" install -q -r "$APP_DIR/requirements.lock"
fi
sudo -u "$APP_USER" "$APP_DIR/.venv/bin/pip" install -q -e "$APP_DIR"

# 5) env file (create once; never clobber the token) ---------------------- #
if [[ ! -f "$ENV_FILE" ]]; then
  log "writing $ENV_FILE (first install)"
  TOKEN="$("$PYTHON" -c 'import secrets;print("hestia_"+secrets.token_urlsafe(32))')"
  cat > "$ENV_FILE" <<EOF
# Hestia runtime config (generated by install.sh on first run).
HESTIA_ENVIRONMENT=prod
HESTIA_DATABASE_URL=sqlite:///${DATA_DIR}/hestia.db
HESTIA_ENABLED_MODULES=dogs,subscriptions

# Humans authenticate at the edge (Authentik in front of hestia.robertonovara.me).
HESTIA_AUTH_MODE=proxy
HESTIA_PROXY_USER_HEADER=X-Authentik-Username
HESTIA_PROXY_EMAIL_HEADER=X-Authentik-Email

# Master agent token for Hermes (the MCP connector sends this as a Bearer).
# Revoke/rotate by replacing it, or issue extra revocable tokens via
# 'scripts.seed --token' (stored hashed in the DB).
HESTIA_AGENT_TOKEN=${TOKEN}

# MCP (the unit also forces transport/host/port).
HESTIA_MCP_REQUIRE_AUTH=true
HESTIA_MCP_AUDIT_ENABLED=true
HESTIA_MCP_AUDIT_LOG_PATH=${DATA_DIR}/mcp-audit.log
EOF
  chown "$APP_USER:$APP_USER" "$ENV_FILE"
  chmod 0640 "$ENV_FILE"
  NEW_TOKEN="$TOKEN"
else
  log "$ENV_FILE already exists — leaving it (and its token) untouched"
fi

# 6) seed the database if empty ------------------------------------------- #
if [[ ! -f "${DATA_DIR}/hestia.db" ]]; then
  log "seeding initial household"
  sudo -u "$APP_USER" env $(grep -v '^#' "$ENV_FILE" | xargs) \
    "$APP_DIR/.venv/bin/python" -m scripts.seed || log "seed reported a non-zero exit (continuing)"
fi
chown -R "$APP_USER:$APP_USER" "$DATA_DIR"

# 7) systemd units -------------------------------------------------------- #
log "installing systemd units"
install -m 0644 "$APP_DIR/deploy/systemd/hestia-api.service" /etc/systemd/system/hestia-api.service
install -m 0644 "$APP_DIR/deploy/systemd/hestia-mcp.service" /etc/systemd/system/hestia-mcp.service
systemctl daemon-reload
systemctl enable --now hestia-api.service
systemctl enable --now hestia-mcp.service

# 8) smoke check ---------------------------------------------------------- #
sleep 2
log "smoke check"
curl -fsS -o /dev/null -w "  api    /api/health -> %{http_code}\n" http://127.0.0.1:8000/api/health || die "API health failed (journalctl -u hestia-api)"
curl -fsS -o /dev/null -w "  mcp    /healthz    -> %{http_code}\n" http://127.0.0.1:8766/healthz   || die "MCP health failed (journalctl -u hestia-mcp)"

log "done."
if [[ -n "${NEW_TOKEN:-}" ]]; then
  echo
  echo "  Hermes agent token (shown once — store it in the claude.ai connector now):"
  echo
  echo "      ${NEW_TOKEN}"
  echo
fi
echo "Next: wire cloudflared + register the connector — see docs/DEPLOY.md (phases 4-5)."
